# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  # Azure service connection established during pipeline creation
  azureSubscription: Azure subscription 1(95a9b8d7-74d7-41e6-bea8-91fcfc7e0bf4)
  appName: app-si-200
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureSubscription)
    ScriptType: 'InlineScript'
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      ls -x

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
      app_location: "/" 
      api_location: ""
      output_location: "build"
  env:
      azure_static_web_apps_api_token: $(static_website_token)
